// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVerse.Context;

namespace MyVerse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211105225906_Verse")]
    partial class Verse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyVerse.Models.Verses", b =>
                {
                    b.Property<string>("Book")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Chapter")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Verse")
                        .HasColumnType("int");

                    b.HasKey("Book");

                    b.ToTable("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
